version: '3'
services:
  react-app: 
    build: .
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    environment:
      - REACT_APP_NAME=Khoa
      - CHOKIDAR_USEPOLLING=true
    # env_file:
    #   - ./.env
  
    

    

  