services:
  app: 
    build: .
    container_name: python-container
    command: python3 -m flask run --host 0.0.0.0 --port 80 --reload
    ports:
      - 80:80
    volumes:
      - .:/code
  db: 
    image: mongo:3.1